<featureType>
  <name>capad10_m_external_all</name>
  <nativeName>capad10_m_external_all</nativeName>
  <namespace>
    <name>oztrack</name>
    <atom:link xmlns:atom="http://www.w3.org/2005/Atom" rel="alternate" href="http://localhost/geoserver/rest/namespaces/oztrack.xml" type="application/xml"/>
  </namespace>
  <title>capad10_m_external_all</title>
  <description>Contents of file</description>
  <keywords>
    <string>features</string>
    <string>capad10_m_external_all</string>
  </keywords>
  <nativeCRS>GEOGCS[&quot;NAD83(CSRS98)&quot;, 
  DATUM[&quot;D_North_American_1983_CSRS98&quot;, 
    SPHEROID[&quot;GRS_1980&quot;, 6378137.0, 298.257222101]], 
  PRIMEM[&quot;Greenwich&quot;, 0.0], 
  UNIT[&quot;degree&quot;, 0.017453292519943295], 
  AXIS[&quot;Longitude&quot;, EAST], 
  AXIS[&quot;Latitude&quot;, NORTH]]</nativeCRS>
  <srs>EPSG:4326</srs>
  <nativeBoundingBox>
    <minx>70.89999999999998</minx>
    <maxx>164.691233333</maxx>
    <miny>-58.449469945999965</miny>
    <maxy>-10.681888948999983</maxy>
    <crs>GEOGCS[&quot;NAD83(CSRS98)&quot;, 
  DATUM[&quot;D_North_American_1983_CSRS98&quot;, 
    SPHEROID[&quot;GRS_1980&quot;, 6378137.0, 298.257222101]], 
  PRIMEM[&quot;Greenwich&quot;, 0.0], 
  UNIT[&quot;degree&quot;, 0.017453292519943295], 
  AXIS[&quot;Longitude&quot;, EAST], 
  AXIS[&quot;Latitude&quot;, NORTH]]</crs>
  </nativeBoundingBox>
  <latLonBoundingBox>
    <minx>70.89999999999998</minx>
    <maxx>164.691233333</maxx>
    <miny>-58.449469945999965</miny>
    <maxy>-10.681888948999983</maxy>
    <crs>GEOGCS[&quot;WGS84(DD)&quot;, 
  DATUM[&quot;WGS84&quot;, 
    SPHEROID[&quot;WGS84&quot;, 6378137.0, 298.257223563]], 
  PRIMEM[&quot;Greenwich&quot;, 0.0], 
  UNIT[&quot;degree&quot;, 0.017453292519943295], 
  AXIS[&quot;Geodetic longitude&quot;, EAST], 
  AXIS[&quot;Geodetic latitude&quot;, NORTH]]</crs>
  </latLonBoundingBox>
  <projectionPolicy>FORCE_DECLARED</projectionPolicy>
  <enabled>true</enabled>
  <metadata>
    <entry key="cachingEnabled">false</entry>
  </metadata>
  <store class="dataStore">
    <name>capad10_m_external_all</name>
    <atom:link xmlns:atom="http://www.w3.org/2005/Atom" rel="alternate" href="http://localhost/geoserver/rest/workspaces/oztrack/datastores/capad10_m_external_all.xml" type="application/xml"/>
  </store>
  <maxFeatures>0</maxFeatures>
  <numDecimals>0</numDecimals>
  <attributes>
    <attribute>
      <name>the_geom</name>
      <minOccurs>0</minOccurs>
      <maxOccurs>1</maxOccurs>
      <nillable>true</nillable>
      <binding>com.vividsolutions.jts.geom.MultiPolygon</binding>
    </attribute>
    <attribute>
      <name>OBJECTID</name>
      <minOccurs>0</minOccurs>
      <maxOccurs>1</maxOccurs>
      <nillable>true</nillable>
      <binding>java.lang.Long</binding>
      <length>10</length>
    </attribute>
    <attribute>
      <name>PA_ID</name>
      <minOccurs>0</minOccurs>
      <maxOccurs>1</maxOccurs>
      <nillable>true</nillable>
      <binding>java.lang.String</binding>
      <length>10</length>
    </attribute>
    <attribute>
      <name>NAME</name>
      <minOccurs>0</minOccurs>
      <maxOccurs>1</maxOccurs>
      <nillable>true</nillable>
      <binding>java.lang.String</binding>
      <length>254</length>
    </attribute>
    <attribute>
      <name>TYPE</name>
      <minOccurs>0</minOccurs>
      <maxOccurs>1</maxOccurs>
      <nillable>true</nillable>
      <binding>java.lang.String</binding>
      <length>60</length>
    </attribute>
    <attribute>
      <name>TYPE_ABBR</name>
      <minOccurs>0</minOccurs>
      <maxOccurs>1</maxOccurs>
      <nillable>true</nillable>
      <binding>java.lang.String</binding>
      <length>10</length>
    </attribute>
    <attribute>
      <name>IUCN</name>
      <minOccurs>0</minOccurs>
      <maxOccurs>1</maxOccurs>
      <nillable>true</nillable>
      <binding>java.lang.String</binding>
      <length>5</length>
    </attribute>
    <attribute>
      <name>NRS_PA</name>
      <minOccurs>0</minOccurs>
      <maxOccurs>1</maxOccurs>
      <nillable>true</nillable>
      <binding>java.lang.String</binding>
      <length>5</length>
    </attribute>
    <attribute>
      <name>GAZ_AREA</name>
      <minOccurs>0</minOccurs>
      <maxOccurs>1</maxOccurs>
      <nillable>true</nillable>
      <binding>java.lang.Double</binding>
      <length>19</length>
    </attribute>
    <attribute>
      <name>GIS_AREA</name>
      <minOccurs>0</minOccurs>
      <maxOccurs>1</maxOccurs>
      <nillable>true</nillable>
      <binding>java.lang.Double</binding>
      <length>19</length>
    </attribute>
    <attribute>
      <name>REPT_AREA</name>
      <minOccurs>0</minOccurs>
      <maxOccurs>1</maxOccurs>
      <nillable>true</nillable>
      <binding>java.lang.Double</binding>
      <length>19</length>
    </attribute>
    <attribute>
      <name>GAZ_DATE</name>
      <minOccurs>0</minOccurs>
      <maxOccurs>1</maxOccurs>
      <nillable>true</nillable>
      <binding>java.lang.String</binding>
      <length>10</length>
    </attribute>
    <attribute>
      <name>LATEST_GAZ</name>
      <minOccurs>0</minOccurs>
      <maxOccurs>1</maxOccurs>
      <nillable>true</nillable>
      <binding>java.lang.String</binding>
      <length>10</length>
    </attribute>
    <attribute>
      <name>STATE</name>
      <minOccurs>0</minOccurs>
      <maxOccurs>1</maxOccurs>
      <nillable>true</nillable>
      <binding>java.lang.String</binding>
      <length>4</length>
    </attribute>
    <attribute>
      <name>AUTHORITY</name>
      <minOccurs>0</minOccurs>
      <maxOccurs>1</maxOccurs>
      <nillable>true</nillable>
      <binding>java.lang.String</binding>
      <length>15</length>
    </attribute>
    <attribute>
      <name>DATASOURCE</name>
      <minOccurs>0</minOccurs>
      <maxOccurs>1</maxOccurs>
      <nillable>true</nillable>
      <binding>java.lang.String</binding>
      <length>20</length>
    </attribute>
    <attribute>
      <name>GOVERNANCE</name>
      <minOccurs>0</minOccurs>
      <maxOccurs>1</maxOccurs>
      <nillable>true</nillable>
      <binding>java.lang.String</binding>
      <length>15</length>
    </attribute>
    <attribute>
      <name>COMMENTS</name>
      <minOccurs>0</minOccurs>
      <maxOccurs>1</maxOccurs>
      <nillable>true</nillable>
      <binding>java.lang.String</binding>
      <length>120</length>
    </attribute>
    <attribute>
      <name>ENVIRON</name>
      <minOccurs>0</minOccurs>
      <maxOccurs>1</maxOccurs>
      <nillable>true</nillable>
      <binding>java.lang.String</binding>
      <length>3</length>
    </attribute>
    <attribute>
      <name>X_COORD</name>
      <minOccurs>0</minOccurs>
      <maxOccurs>1</maxOccurs>
      <nillable>true</nillable>
      <binding>java.lang.Double</binding>
      <length>19</length>
    </attribute>
    <attribute>
      <name>Y_COORD</name>
      <minOccurs>0</minOccurs>
      <maxOccurs>1</maxOccurs>
      <nillable>true</nillable>
      <binding>java.lang.Double</binding>
      <length>19</length>
    </attribute>
    <attribute>
      <name>MGT_PLAN</name>
      <minOccurs>0</minOccurs>
      <maxOccurs>1</maxOccurs>
      <nillable>true</nillable>
      <binding>java.lang.String</binding>
      <length>3</length>
    </attribute>
    <attribute>
      <name>RES_NUMBER</name>
      <minOccurs>0</minOccurs>
      <maxOccurs>1</maxOccurs>
      <nillable>true</nillable>
      <binding>java.lang.String</binding>
      <length>15</length>
    </attribute>
    <attribute>
      <name>SHAPE_AREA</name>
      <minOccurs>0</minOccurs>
      <maxOccurs>1</maxOccurs>
      <nillable>true</nillable>
      <binding>java.lang.Double</binding>
      <length>19</length>
    </attribute>
    <attribute>
      <name>SHAPE_LEN</name>
      <minOccurs>0</minOccurs>
      <maxOccurs>1</maxOccurs>
      <nillable>true</nillable>
      <binding>java.lang.Double</binding>
      <length>19</length>
    </attribute>
  </attributes>
</featureType>