<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <description>Generated by OzTrack ${baseUrl}/</description>
    <#list analysis.animals as animal>
    <Style id="animal-${animal.id?c}">
      <#assign animalKmlColour="${animal.colour?substring(5,7)}${animal.colour?substring(3,5)}${animal.colour?substring(1,3)}"/>
      <LineStyle>
        <color>cc${animalKmlColour}</color>
        <width>2</width>
      </LineStyle>
      <PolyStyle>
        <color>7f${animalKmlColour}</color>
        <fill><#if fill>1<#else>0</#if></fill>
        <outline>1</outline>
      </PolyStyle>
    </Style>
    </#list>
    <Schema name="Analysis" id="Analysis">
      <SimpleField name="id" type="string"/>
      <#list analysis.analysisType.featureResultAttributeTypes as resultAttributeType>
      <SimpleField name="${resultAttributeType.identifier}" type="${resultAttributeType.dataType}"/>
      </#list>
    </Schema>
    <#list analysis.resultFeatures as resultFeature>
    <Placemark>
      <styleUrl>#animal-${resultFeature.animal.id?c}</styleUrl>
      <name>${resultFeature.animal.animalName}</name>
      <visibility>1</visibility>
      <ExtendedData>
        <SchemaData schemaUrl="#Analysis">
          <SimpleData name="id">${resultFeature.animal.id?c}</SimpleData>
          <SimpleData name="animalName">${resultFeature.animal.animalName}</SimpleData>
          <#list analysis.analysisType.featureResultAttributeTypes as resultAttributeType>
          <SimpleData name="${resultAttributeType.identifier}">${resultFeature.getAttributeValue(resultAttributeType.identifier)?c}</SimpleData>
          </#list>
        </SchemaData>
      </ExtendedData>
      <MultiGeometry>
        <#list 0..(resultFeature.geometry.numGeometries - 1) as n>
        <Polygon>
          <outerBoundaryIs>
            <LinearRing>
              <coordinates>
                <#list resultFeature.geometry.getGeometryN(n).coordinates as coordinate>
                ${coordinate.x?c},${coordinate.y?c}
                </#list>
              </coordinates>
            </LinearRing>
          </outerBoundaryIs>
        </Polygon>
        </#list>
      </MultiGeometry>
    </Placemark>
    </#list>
  </Document>
</kml>