<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <description>Generated by OzTrack ${baseUrl}/</description>
    <#assign animal=analysis.animals[0]/>
    <Style id="animal-${animal.id?c}">
      <#assign animalKmlColour="${animal.colour?substring(5,7)}${animal.colour?substring(3,5)}${animal.colour?substring(1,3)}"/>
      <IconStyle>
        <color>cc${animalKmlColour}</color>
        <scale>0.8</scale>
        <Icon>
          <href>http://maps.google.com/mapfiles/kml/shapes/placemark_circle.png</href>
        </Icon>
      </IconStyle>
    </Style>
    <Schema name="KalmanFilter" id="KalmanFilter">
      <SimpleField name="id" type="string"/>
      <#list analysis.analysisType.overallResultAttributeTypes as resultAttributeType>
      <SimpleField name="${resultAttributeType.identifier}" type="${resultAttributeType.dataType}"/>
      </#list>
    </Schema>
    <ExtendedData>
      <SchemaData schemaUrl="#KalmanFilter">
        <#list analysis.analysisType.overallResultAttributeTypes as resultAttributeType>
        <SimpleData name="${resultAttributeType.identifier}">${analysis.getResultAttributeValue(resultAttributeType.identifier)?c}</SimpleData>
        </#list>
      </SchemaData>
    </ExtendedData>
    <#list analysis.resultFeatures as resultFeature>
    <Placemark>
      <styleUrl>#animal-${resultFeature.animal.id?c}</styleUrl>
      <visibility>1</visibility>
      <TimeStamp>
        <when>${resultFeature.dateTime?iso_local_nz}</when>
      </TimeStamp>
      <ExtendedData>
        <SchemaData schemaUrl="#Analysis">
          <SimpleData name="id">${resultFeature.animal.id?c}</SimpleData>
          <#list analysis.analysisType.featureResultAttributeTypes as resultAttributeType>
          <SimpleData name="${resultAttributeType.identifier}">${resultFeature.getAttributeValue(resultAttributeType.identifier)?c}</SimpleData>
          </#list>
        </SchemaData>
      </ExtendedData>
      <Point>
        <coordinates>
           ${resultFeature.geometry.x},${resultFeature.geometry.y}
        </coordinates>
      </Point>
    </Placemark>
    </#list>
  </Document>
</kml>