<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <description>Generated by OzTrack ${baseUrl}/</description>
    <#assign animal=analysis.animals[0]/>
    <Style id="animal-${animal.id?c}-trajectory">
      <LineStyle>
        <color>ffffffff</color>
        <width>2</width>
      </LineStyle>
    </Style>
    <Style id="animal-${animal.id?c}-detection">
      <IconStyle>
        <color>ffffffff</color>
        <scale>0.5</scale>
        <Icon>
          <href>http://maps.google.com/mapfiles/kml/shapes/triangle.png</href>
        </Icon>
      </IconStyle>
    </Style>
    <Schema name="Overall" id="Overall">
      <SimpleField name="id" type="string"/>
      <#list analysis.analysisType.overallResultAttributeTypes as resultAttributeType>
      <SimpleField name="${resultAttributeType.identifier}" type="${resultAttributeType.dataType}"/>
      </#list>
    </Schema>
    <Schema name="Feature" id="Feature">
      <SimpleField name="id" type="string"/>
      <#list analysis.analysisType.featureResultAttributeTypes as resultAttributeType>
      <SimpleField name="${resultAttributeType.identifier}" type="${resultAttributeType.dataType}"/>
      </#list>
    </Schema>
    <Placemark>
      <name>Trajectory</name>
      <styleUrl>#animal-${animal.id?c}-trajectory</styleUrl>
      <TimeSpan>
        <begin>${analysis.resultFeatures?first.dateTime?iso_local_nz}</begin>
        <end>${analysis.resultFeatures?last.dateTime?iso_local_nz}</end>
      </TimeSpan>
      <ExtendedData>
        <SchemaData schemaUrl="#Overall">
          <SimpleData name="id">${animal.id?c}</SimpleData>
          <#list analysis.analysisType.overallResultAttributeTypes as resultAttributeType>
          <SimpleData name="${resultAttributeType.identifier}"><#rt>
          <#if (analysis.getResultAttributeValue(resultAttributeType.identifier)??)><#t>
          ${analysis.getResultAttributeValue(resultAttributeType.identifier)?c}<#t>
          </#if><#t>
          </SimpleData><#lt>
          </#list>
        </SchemaData>
      </ExtendedData>
      <LineString>
        <coordinates>
          <#list analysis.resultFeatures as resultFeature>
          ${resultFeature.geometry.x?c},${resultFeature.geometry.y?c}
          </#list>
        </coordinates>
      </LineString>
    </Placemark>
    <Folder>
      <name>Detections</name>
      <#list analysis.resultFeatures as resultFeature>
      <Placemark>
        <styleUrl>#animal-${resultFeature.animal.id?c}-detection</styleUrl>
        <TimeStamp>
          <when>${resultFeature.dateTime?iso_local_nz}</when>
        </TimeStamp>
        <ExtendedData>
          <SchemaData schemaUrl="#Feature">
            <SimpleData name="id">${resultFeature.animal.id?c}</SimpleData>
            <#list analysis.analysisType.featureResultAttributeTypes as resultAttributeType>
            <SimpleData name="${resultAttributeType.identifier}"><#rt>
            <#if (resultFeature.getAttributeValue(resultAttributeType.identifier)??)><#t>
            ${resultFeature.getAttributeValue(resultAttributeType.identifier)?c}<#t>
            </#if><#t>
            </SimpleData><#lt>
            </#list>
          </SchemaData>
        </ExtendedData>
        <Point>
          <coordinates>
             ${resultFeature.geometry.x?c},${resultFeature.geometry.y?c}
          </coordinates>
        </Point>
      </Placemark>
      </#list>
    </Folder>
  </Document>
</kml>