<coverage>
  <name>cars2009a_salinity</name>
  <nativeName>cars2009a_salinity</nativeName>
  <namespace>
    <name>oztrack</name>
  </namespace>
  <title>cars2009a_salinity</title>
  <description>Generated from GeoTIFF</description>
  <keywords>
    <string>WCS</string>
    <string>GeoTIFF</string>
    <string>cars2009a_salinity</string>
  </keywords>
  <nativeCRS class="org.geotools.referencing.crs.DefaultEngineeringCRS">LOCAL_CS[&quot;Wildcard 2D cartesian plane in metric unit&quot;, 
  LOCAL_DATUM[&quot;Unknown&quot;, 0], 
  UNIT[&quot;m&quot;, 1.0], 
  AXIS[&quot;x&quot;, EAST], 
  AXIS[&quot;y&quot;, NORTH], 
  AUTHORITY[&quot;EPSG&quot;,&quot;404000&quot;]]</nativeCRS>
  <srs>EPSG:4326</srs>
  <nativeBoundingBox>
    <minx>0.0</minx>
    <maxx>360.0</maxx>
    <miny>-90.0</miny>
    <maxy>90.0</maxy>
    <crs>EPSG:4326</crs>
  </nativeBoundingBox>
  <latLonBoundingBox>
    <minx>-180.0</minx>
    <maxx>180.0</maxx>
    <miny>-90.0</miny>
    <maxy>90.0</maxy>
    <crs>GEOGCS[&quot;WGS84(DD)&quot;, 
  DATUM[&quot;WGS84&quot;, 
    SPHEROID[&quot;WGS84&quot;, 6378137.0, 298.257223563]], 
  PRIMEM[&quot;Greenwich&quot;, 0.0], 
  UNIT[&quot;degree&quot;, 0.017453292519943295], 
  AXIS[&quot;Geodetic longitude&quot;, EAST], 
  AXIS[&quot;Geodetic latitude&quot;, NORTH]]</crs>
  </latLonBoundingBox>
  <projectionPolicy>FORCE_DECLARED</projectionPolicy>
  <enabled>true</enabled>
  <advertised>true</advertised>
  <metadata>
    <entry key="time">
      <dimensionInfo>
        <enabled>false</enabled>
      </dimensionInfo>
    </entry>
    <entry key="cachingEnabled">false</entry>
    <entry key="elevation">
      <dimensionInfo>
        <enabled>false</enabled>
      </dimensionInfo>
    </entry>
    <entry key="dirName">cars2009a_salinity_cars2009a_salinity</entry>
  </metadata>
  <store class="coverageStore">
    <name>cars2009a_salinity</name>
  </store>
  <nativeFormat>GeoTIFF</nativeFormat>
  <grid dimension="2">
    <range>
      <low>0 0</low>
      <high>721 331</high>
    </range>
    <transform>
      <scaleX>0.5</scaleX>
      <scaleY>-0.5</scaleY>
      <shearX>0.0</shearX>
      <shearY>0.0</shearY>
      <translateX>0.0</translateX>
      <translateY>90.0</translateY>
    </transform>
    <crs>EPSG:4326</crs>
  </grid>
  <supportedFormats>
    <string>GIF</string>
    <string>PNG</string>
    <string>JPEG</string>
    <string>TIFF</string>
    <string>GEOTIFF</string>
  </supportedFormats>
  <interpolationMethods>
    <string>bilinear</string>
    <string>bicubic</string>
  </interpolationMethods>
  <dimensions>
    <coverageDimension>
      <name>Band1</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band2</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band3</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band4</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band5</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band6</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band7</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band8</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band9</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band10</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band11</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band12</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band13</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band14</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band15</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band16</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band17</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band18</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band19</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band20</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band21</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band22</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band23</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band24</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band25</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band26</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band27</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band28</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band29</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band30</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band31</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band32</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band33</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band34</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band35</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band36</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band37</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band38</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band39</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band40</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band41</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band42</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band43</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band44</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band45</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band46</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band47</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band48</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band49</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band50</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band51</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band52</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band53</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band54</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band55</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band56</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band57</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band58</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band59</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band60</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band61</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band62</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band63</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band64</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band65</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band66</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band67</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band68</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band69</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band70</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band71</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band72</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band73</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band74</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band75</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band76</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band77</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band78</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
    <coverageDimension>
      <name>Band79</name>
      <description>GridSampleDimension[-32767.0,-32767.0]</description>
      <range>
        <min>-32767.0</min>
        <max>-32767.0</max>
      </range>
      <nullValues>
        <double>-32767.0</double>
      </nullValues>
    </coverageDimension>
  </dimensions>
  <requestSRS>
    <string>EPSG:404000</string>
  </requestSRS>
  <responseSRS>
    <string>EPSG:404000</string>
  </responseSRS>
  <parameters>
    <entry>
      <string>InputTransparentColor</string>
      <string></string>
    </entry>
    <entry>
      <string>SUGGESTED_TILE_SIZE</string>
      <string>512,512</string>
    </entry>
  </parameters>
</coverage>